# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a77e9bd3d5975dec4ced10a18d99d83a11aa748978035e2c476029be48dc70556cb0e501e7affb8b0feb0865a0db18f88e2b49d0bb9f392a42e915c4948608f8

test:
  secret_key_base: 39553b88aa99ff734d7af6557d67e4ea88df383b5e08d1c753318f05838703487a382bfc47eb0575751d36486c37eb20587863786bf84dac0333d0f8979156b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
